#!/bin/bash
# foneadd -- add records to ~/fone
# v2: backup created, sorted copy to ~/fone
# vs removed duplicate lines 
# v4 -- take arguments off command line
# v5 -- add date to end of each record
# v5.1 -- all file references must use full path
if [ "$1" != "" ]; then FNAME=$1
 else echo -n "Enter First name: " ; read FNAME; fi
if [ "$2" != "" ];  then LNAME=$2
else echo -n "Enter last  name: " ; read LNAME; fi
if [ "$3" != "" ];  then FONE=$3
else  echo -n "Enter fone      : " ; read FONE; fi
echo $FNAME $LNAME $FONE $(date +%y%m%d) >>  ~/fone
sort -u ~/fone > ~/fone.tmp 
mv ~/fone ~/fone.bck -f; mv ~/fone.tmp ~/fone
echo Added and sorted to ~/fone: $FNAME $LNAME $FONE $(date):

