#!/bin/bash
# fonedel -- remove one or more entries in ~/fone
# v2 - ask if no entry $1, confirm deletion
# v2.1 -- fixed to use DELANS in deletion instead of ANS
if [ "$1" = "" ]
 then
  echo -n "Delete/remove what? : " ; read DELANS
 else
  DELANS="$1"
fi
echo Will remove      the following    details
grep -i "$DELANS" ~/fone
echo -n "Provide 'Y' or 'y' plus ENTER to confirm, anything else to skip : "; read ANS
if [ "$ANS" = "Y" -o "$ANS" = "y" ]
 then
  grep -iv "$DELANS" ~/fone > ~/fone.tmp
	mv ~/fone ~/fone.bck-$(date +%y%m%d)
	mv ~/fone.tmp ~/fone
 else
  echo skipping removal of : $DELANS :
	exit 2
fi
exit 0

