#!/bin/bash
# fonemenu -- display all fone programs in menu to select
# v2 added view option
while [ 1 ]
 do
 clear
 cat <<EOF
************************************************************
 
EOF
 echo -n \
  "Options [a|A]dd,[f|F]ind,[d|D]elete,[u|U]pdate,[v|V]iew,[q|Q]uit : "
                              read ANS
      echo
 echo '***********************************************************'
 case $ANS in
   A*|a*) echo "USAGE: foneadd [first [last [phone]]]]" ; echo ; foneadd ;;
   F*|f*) echo "USAGE: fonefind ANYstringINfile" ; echo ; fonefind ;;
   D*|d*) echo "USAGE: fonedel [first [last [phone]]]]" ; echo ; fonedel ;;
   U*|u*) echo "USAGE: fonemod [specificOnePlusItems]" ; echo ; fonemod ;;
   V*|v*) echo "USAGE: foneview" ; echo ; foneview ;;
	 Q*|q*) exit 0 ;;
	 *) echo "Try again, only [AaDdFfQq] based options available, press ENTER";;
 esac
 read NN 
done
